"""Generate native-speaker review docs for exercise content.

Produces two Markdown files under docs/reviews/:

* exercise-reference.md — representative exercises across every module,
  grouped by taxonomy branch. ~66 rows total. For cross-module review.
* time-reference.md — exhaustive enumeration of all 48 time expressions
  (12 hours × 4 types). Replaces the retired time_reference.py.

Run from the repo root:

    uv run python scripts/generate_exercise_reference.py

Both output files are overwritten. The committed copies are gated by
tests/test_regressions.py::test_exercise_reference_docs_in_sync.
"""

from __future__ import annotations

import datetime as _dt
import sys
from pathlib import Path

# Make the repo root importable so the engine modules resolve.
_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

from adaptive import AdaptiveLearning  # noqa: E402
from age_engine import PRONOUNS as AGE_PRONOUNS  # noqa: E402
from age_engine import AgeEngine  # noqa: E402
from fastlite import database  # noqa: E402
from number_engine import NumberEngine  # noqa: E402
from quiz import ExerciseEngine  # noqa: E402
from time_engine import TIME_TYPES, TimeEngine  # noqa: E402
from weather_engine import WeatherEngine  # noqa: E402

# ---------------------------------------------------------------------
# Row loading
# ---------------------------------------------------------------------

_DB_PATH = _REPO_ROOT / "lithuanian_data.db"


def _load_rows() -> list[dict]:
    db = database(str(_DB_PATH))
    return list(db.t["numbers"].rows)


def _row(rows: list[dict], n: int) -> dict:
    for r in rows:
        if r["number"] == n:
            return r
    msg = f"no row for number={n} in lithuanian_data.db"
    raise LookupError(msg)


# ---------------------------------------------------------------------
# Representative tuples — edit these to add / refine review coverage
# ---------------------------------------------------------------------
# Numbers: (exercise_type, number)
_NUMBERS_REP = [
    ("produce", 0),
    ("produce", 5),
    ("recognize", 7),
    ("produce", 13),
    ("recognize", 19),
    ("produce", 20),
    ("recognize", 50),
    ("produce", 21),
    ("produce", 45),
    ("recognize", 99),
]

# Age: (exercise_type, number, pronoun_dative)
_AGE_REP = [
    ("produce", 2, "Man"),
    ("produce", 5, "Tau"),
    ("produce", 9, "Jam"),
    ("produce", 15, "Jai"),
    ("produce", 20, "Man"),
    ("produce", 21, "Tau"),
    ("produce", 22, "Jam"),
    ("produce", 45, "Jai"),
    ("recognize", 10, "Man"),
    ("recognize", 33, "Tau"),
]

# Weather: (exercise_type, number, negative)
_WEATHER_REP = [
    ("produce", 0, False),
    ("produce", 5, False),
    ("produce", 15, False),
    ("produce", 25, False),
    ("produce", 1, True),
    ("produce", 10, True),
    ("produce", 15, True),
    ("recognize", 7, False),
    ("recognize", 12, True),
]

# Prices: (exercise_type in {"kokia", "kiek"}, number, item)
_PRICES_REP = [
    ("kokia", 1, None),
    ("kokia", 5, None),
    ("kokia", 15, None),
    ("kokia", 21, None),
    ("kokia", 45, None),
    ("kokia", 99, None),
    ("kiek", 1, "knyga"),
    ("kiek", 5, "knyga"),
    ("kiek", 15, "knyga"),
    ("kiek", 21, "knyga"),
    ("kiek", 45, "knyga"),
]


# ---------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------


def _md_table(rows: list[tuple[str, str, str]]) -> str:
    """Return a Markdown table given rows of (exercise, prompt, correct)."""
    out = ["| Exercise | Prompt | Correct answer |", "|---|---|---|"]
    for ex, prompt, correct in rows:
        out.append(f"| {ex} | {prompt} | {correct} |")
    return "\n".join(out)


def _pronoun_dict(dative: str) -> dict[str, str]:
    for p in AGE_PRONOUNS:
        if p["dative"] == dative:
            return p
    msg = f"unknown pronoun dative: {dative!r}"
    raise LookupError(msg)


_TIME_MINUTES = {
    "whole_hour": 0,
    "quarter_past": 15,
    "half_past": 30,
    "quarter_to": 45,
}


# ---------------------------------------------------------------------
# Build the representative doc
# ---------------------------------------------------------------------


def _build_exercise_reference(rows: list[dict]) -> str:
    today = _dt.date.today().isoformat()
    out = [
        f"<!-- Generated by scripts/generate_exercise_reference.py on {today}. "
        f"Do not edit by hand. -->",
        "",
        "# Exercise Reference — for Native-Speaker Review",
        "",
        "Representative exercises across every module, grouped by taxonomy "
        "branch. Each row shows the prompt the learner sees and the exact "
        "Lithuanian answer the app accepts. Review for correctness / "
        "naturalness — flag anything that reads wrong.",
        "",
    ]

    # ---- Numbers
    num_engine = NumberEngine(rows)
    out += ["## Numbers (/numbers)", ""]
    out += [
        "Range 0–99. Two exercise types: `produce` (say the number in "
        "Lithuanian) and `recognize` (identify the number from its "
        "Lithuanian form).",
        "",
    ]
    num_rows: list[tuple[str, str, str]] = []
    for ex_type, n in _NUMBERS_REP:
        row = _row(rows, n)
        prompt = num_engine.format_question(ex_type, row, lang="en")
        correct = num_engine.correct_answer(ex_type, row)
        num_rows.append((ex_type, prompt, correct))
    out += [_md_table(num_rows), ""]

    # ---- Age
    age_rows_src = [r for r in rows if r["number"] >= 2]
    age_engine = AgeEngine(age_rows_src)
    out += ["## Age (/age)", ""]
    out += [
        "Ages 2–99 with dative pronouns (Man, Tau, Jam, Jai). Numbers 1–9 "
        "and compound ones-digits 1–9 pair with collective numerals "
        "(dveji, treji, …) and the noun `metai`; 10–19 and round tens "
        "use cardinal numerals with the noun `metų`.",
        "",
    ]
    age_rows: list[tuple[str, str, str]] = []
    for ex_type, n, dative in _AGE_REP:
        row = _row(rows, n)
        pronoun = _pronoun_dict(dative)
        prompt = age_engine.format_question(ex_type, row, pronoun, lang="en")
        correct = age_engine.correct_answer(ex_type, row, pronoun)
        age_rows.append((ex_type, prompt, correct))
    out += [_md_table(age_rows), ""]

    # ---- Weather
    weather_rows_src = [r for r in rows if r["number"] >= 0]
    weather_engine = WeatherEngine(weather_rows_src)
    out += ["## Weather (/weather)", ""]
    out += [
        "Temperatures from –20 °C to +99 °C. `produce` prompts say "
        "'How do you say … °C?'; `recognize` prompts show a Lithuanian "
        "phrase and ask for the numeric answer. Negative is prefixed "
        "with 'minus'; the degree word inflects (laipsnis / laipsniai / "
        "laipsnių).",
        "",
    ]
    weather_rows: list[tuple[str, str, str]] = []
    for ex_type, n, negative in _WEATHER_REP:
        row = _row(rows, n)
        prompt = weather_engine.format_question(
            ex_type, row, negative=negative, lang="en"
        )
        correct = weather_engine.correct_answer(ex_type, row, negative=negative)
        weather_rows.append((ex_type, prompt, correct))
    out += [_md_table(weather_rows), ""]

    # ---- Prices
    price_rows_src = [r for r in rows if r["number"] >= 1]
    price_engine = ExerciseEngine(price_rows_src, AdaptiveLearning())
    out += ["## Prices (/prices)", ""]
    out += [
        "Two cases: `kokia` (nominative — stating the price directly) and "
        "`kiek` (accusative — saying what something costs, where the "
        "number word declines).",
        "",
    ]
    price_rows: list[tuple[str, str, str]] = []
    for ex_type, n, item in _PRICES_REP:
        row = _row(rows, n)
        price_str = f"€{n}"
        prompt = price_engine.format_question(ex_type, price_str, item)
        correct = price_engine.correct_answer(ex_type, row)
        price_rows.append((ex_type, prompt, correct))
    out += [_md_table(price_rows), ""]

    # ---- Time (preview; exhaustive file is separate)
    out += ["## Time (/time)", ""]
    out += [
        "Representative samples below; the full 48-expression enumeration "
        "(every hour × every time type) is in `docs/reviews/time-reference.md`.",
        "",
    ]
    time_engine = TimeEngine()
    time_rows: list[tuple[str, str, str]] = []
    for time_type in TIME_TYPES:
        for hour in (1, 6, 12):
            minute = _TIME_MINUTES[time_type]
            display = f"{hour}:{minute:02d}"
            prompt = time_engine.format_question(display)
            correct = time_engine.correct_answer(time_type, hour, minute)
            time_rows.append((time_type, prompt, correct))
    out += [_md_table(time_rows), ""]

    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------
# Build the exhaustive time doc
# ---------------------------------------------------------------------


def _build_time_reference() -> str:
    today = _dt.date.today().isoformat()
    time_engine = TimeEngine()
    out = [
        f"<!-- Generated by scripts/generate_exercise_reference.py on {today}. "
        f"Do not edit by hand. -->",
        "",
        "# Time Reference — Exhaustive",
        "",
        "Every time expression the `/time` module can produce: 12 hours × "
        "4 time types = 48 entries. Replaces the retired "
        "`time_reference.py`.",
        "",
    ]

    type_labels = {
        "whole_hour": "Whole hour (nominative + valanda)",
        "quarter_past": "Quarter past (ketvirtis + genitive of next hour)",
        "half_past": "Half past (pusė + genitive of next hour)",
        "quarter_to": "Quarter to (be ketvirčio + nominative of next hour)",
    }

    for time_type in TIME_TYPES:
        out += [f"## {type_labels[time_type]}", ""]
        minute = _TIME_MINUTES[time_type]
        out += [
            "| Hour | Prompt | Correct answer |",
            "|---|---|---|",
        ]
        for hour in range(1, 13):
            display = f"{hour}:{minute:02d}"
            prompt = time_engine.format_question(display)
            correct = time_engine.correct_answer(time_type, hour, minute)
            out.append(f"| hour={hour} | {prompt} | {correct} |")
        out += [""]

    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------


def main() -> None:
    rows = _load_rows()
    exercise_doc = _build_exercise_reference(rows)
    time_doc = _build_time_reference()

    reviews_dir = _REPO_ROOT / "docs" / "reviews"
    reviews_dir.mkdir(parents=True, exist_ok=True)
    (reviews_dir / "exercise-reference.md").write_text(exercise_doc)
    (reviews_dir / "time-reference.md").write_text(time_doc)

    print(f"wrote {reviews_dir / 'exercise-reference.md'}")
    print(f"wrote {reviews_dir / 'time-reference.md'}")


if __name__ == "__main__":
    main()
